### ISSUE TITLE
ISE during formatting of long lambda with named parameter

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-core#527] opened 2017-11-06 12:41 UTC
Trying to format the following Xtend code causes a [NPE](https://github.com/eclipse/xtext-core/files/1446202/XtendFormatting.txt)
```xtend
class test {
	val static SUPER_LONG_LIST_TO_TEST_IF_FORMATTING_WORKS_HERE_AND_SUCH = #[]
	def      fn() {
		return SUPER_LONG_LIST_TO_TEST_IF_FORMATTING_WORKS_HERE_AND_SUCH.map[l | SUPER_LONG_LIST_TO_TEST_IF_FORMATTING_WORKS_HERE_AND_SUCH]
	}
}
```

**Comment by cdietrich** [comment] 2017-11-08 12:31
am not getting a npe but

```
6    [main] ERROR org.eclipse.xtext.ui.editor.formatting2.ContentFormatter$FormattingUnitOfWork  - Error formatting platform:/resource/abc/src/abc/Hugo.xtend: null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:907)
	at java.util.ArrayList$Itr.next(ArrayList.java:857)
	at com.google.common.collect.Iterators$3.next(Iterators.java:174)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.createReplacements(FormattableDocument.java:130)
	at org.eclipse.xtext.formatting2.internal.SubDocument.createReplacements(SubDocument.java:38)
	at org.eclipse.xtext.formatting2.internal.MaxLineWidthDocument.createReplacements(MaxLineWidthDocument.java:38)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.createReplacements(FormattableDocument.java:146)
	at org.eclipse.xtext.formatting2.internal.SubDocument.createReplacements(SubDocument.java:38)
	at org.eclipse.xtext.formatting2.internal.ConditionalReplacer.createReplacements(ConditionalReplacer.java:43)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.createReplacements(FormattableDocument.java:146)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.renderToTextReplacements(FormattableDocument.java:293)
	at org.eclipse.xtext.formatting2.AbstractFormatter2.format(AbstractFormatter2.java:275)
	at org.eclipse.xtext.ui.editor.formatting2.ContentFormatter.exec(ContentFormatter.java:90)
	at org.eclipse.xtext.ui.editor.formatting2.ContentFormatter$FormattingUnitOfWork.exec(ContentFormatter.java:57)
	at org.eclipse.xtext.ui.editor.formatting2.ContentFormatter$FormattingUnitOfWork.exec(ContentFormatter.java:1)
```

**Comment by tivervac** [comment] 2017-11-08 12:43
That's the same I got, got confused because the message mentions null:
org.eclipse.xtext.ui.editor.formatting2.ContentFormatter$FormattingUnitOfWork  - Error formatting platform:/resource/com.sigasi.hdt.vhdl.ui/src/com/sigasi/hdt/vhdl/ui/builder/test.xtend: null

**Comment by cdietrich** [comment] 2017-11-08 12:51
here is the trace that adds an additional replacer:

```
java.lang.IllegalStateException
	at org.eclipse.xtext.formatting2.internal.ArrayListTextSegmentSet.add(ArrayListTextSegmentSet.java:44)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.addReplacer(FormattableDocument.java:78)
	at org.eclipse.xtext.formatting2.internal.MaxLineWidthDocument.addReplacer(MaxLineWidthDocument.java:33)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.set(FormattableDocument.java:323)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.append(FormattableDocument.java:88)
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter.formatClosureParams(XbaseFormatter.java:1080)
	at org.eclipse.xtext.xbase.formatting2.XbaseFormatter.lambda$121(XbaseFormatter.java:1200)
	at org.eclipse.xtext.formatting2.internal.ConditionalReplacer.createReplacements(ConditionalReplacer.java:41)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.createReplacements(FormattableDocument.java:148)
	at org.eclipse.xtext.formatting2.internal.SubDocument.createReplacements(SubDocument.java:38)
	at org.eclipse.xtext.formatting2.internal.MaxLineWidthDocument.createReplacements(MaxLineWidthDocument.java:38)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.createReplacements(FormattableDocument.java:148)
	at org.eclipse.xtext.formatting2.internal.SubDocument.createReplacements(SubDocument.java:38)
	at org.eclipse.xtext.formatting2.internal.ConditionalReplacer.createReplacements(ConditionalReplacer.java:43)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.createReplacements(FormattableDocument.java:148)
	at org.eclipse.xtext.formatting2.internal.FormattableDocument.renderToTextReplacements(FormattableDocument.java:295)
	at org.eclipse.xtext.formatting2.AbstractFormatter2.format(AbstractFormatter2.java:275)
```

**Comment by cdietrich** [comment] 2017-11-29 08:22
see https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/problems/5a1d9313e4b02aaf8b215b2c as well

**Comment by cdietrich** [comment] 2018-06-23 09:33
@meysholdt am not sure if org.eclipse.xtext.formatting2.internal.FormattableDocument.createReplacements(ITextReplacerContext)
should create a copy of the complete iterator before iterating or if we want to be able to lazy add stuff to the replacers list

**Comment by cdietrich** [comment] 2018-06-23 10:04
for me it looks like the problem is in 
```
val last = expr.formatClosureParams(open, format)[oneSpace]
```
in XbaseFormatter, instead of the parameter format i think the closueparmeter
doc == the subdocument should be used.

**Comment by cdietrich** [comment] 2018-06-28 05:05
Fixed in 2.15

**Closed by cdietrich** 2018-06-28 05:05 UTC
Labels: bug, confirmed
