### ISSUE TITLE
Serializer.serializeToRegions() produces invalid output for EObjects without attached node model

### ISSUE THREAD

**Issue by enikao** [eclipse/xtext-core#464] opened 2017-09-19 11:22 UTC
When serializing a pristine EObject (i.e. an EObject that was not loaded from an XtextResource and thus has no attached node model) to regions, no / not enough whitespace is produced. This leads to an invalid result.

In the example below, no spaces are generated at all. In my real-life example, spaces are only missing between two consecutive character-only keywords.

Example grammar (based on empty Xtext project):
```xtext
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model: {Model}
	('greetings'
		greetings+=Greeting*
	'end')?
	
	('more'
		greetings2+=Greeting*
	'end'
	)?
;
	
Greeting:
	'Hello' name=ID '!';
```

Test case:
```xtend
package org.xtext.example.mydsl

import org.eclipse.xtext.serializer.ISerializer
import org.eclipse.xtext.serializer.impl.Serializer
import org.junit.Test
import org.xtext.example.mydsl.myDsl.MyDslFactory

import static org.junit.Assert.*

class TestSerializer {
	extension MyDslFactory factory = MyDslFactory.eINSTANCE
	
	@Test
	def void test() {
		val injector = new MyDslStandaloneSetup().createInjectorAndDoEMFRegistration()
		
		val model = createModel => [
			greetings += createGreeting => [name = 'name1']
			greetings += createGreeting => [name = 'name2']
			greetings2 += createGreeting => [name = 'name3']
			greetings2 += createGreeting => [name = 'name4']
		]
		
		val serializer = injector.getInstance(ISerializer) as Serializer
		
		val regions = serializer.serializeToRegions(model)
		
		val text = regions.regionForDocument.text;
		
		assertEquals("greetings Hello name1! Hello name2! end more Hello name3! Hello name4! end", text)

		// actualResult: "greetingsHelloname1!Helloname2!endmoreHelloname3!Helloname4!end"

	}
}
```

My current workaround is to force spaces after each keyword:
```java
package org.eclipse.xtext.example.fowlerdsl.formatting;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.formatting2.regionaccess.ITextRegionAccess;
import org.eclipse.xtext.formatting2.regionaccess.TextRegionAccessBuilder;
import org.eclipse.xtext.formatting2.regionaccess.internal.TextRegionAccessBuildingSequencer;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.ISequenceAcceptor;
import org.eclipse.xtext.util.Strings;

@SuppressWarnings("restriction")
public class InlineTextRegionAccessBuilder extends TextRegionAccessBuilder {
	private TextRegionAccessBuildingSequencer fromSequencer;

	@Override
	public ISequenceAcceptor forSequence(final ISerializationContext ctx, final EObject root) {
		return this.fromSequencer = new TextRegionAccessBuildingSequencer() {
			@Override
			public void acceptWhitespace(final org.eclipse.xtext.AbstractRule rule, final String token,
					final org.eclipse.xtext.nodemodel.ILeafNode node) {
				if (!Strings.isEmpty(token)) {
					super.acceptWhitespace(rule, token, node);
				} else {
					super.acceptWhitespace(rule, GrammarUtil.containedKeywords(rule).iterator().next().getValue(),
							node);
				}
			};
			
		}.withRoot(ctx, root);
	}

	@Override
	public ITextRegionAccess create() {
		if (this.fromSequencer != null) {
			return this.fromSequencer.getRegionAccess();
		}
		return super.create();
	}
	
}
```

```java
package org.eclipse.xtext.example.fowlerdsl.formatting;

import java.util.List;

import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.sequencer.HiddenTokenSequencer;

@SuppressWarnings("restriction")
public class InlineHiddenTokenSequencer extends HiddenTokenSequencer {
	@Override
	protected void emitHiddenTokens(final List<INode> hiddens) {
		if (hiddens != null) {
			super.emitHiddenTokens(hiddens);
		} else {
			this.delegate.acceptWhitespace(this.hiddenTokenHelper.getWhitespaceRuleFor(null, ""), "", null);
		}
	}
	
}
```

The issue appears at least in Xtext 2.9.1 and 2.12.0.

**Comment by cdietrich** [comment] 2017-09-19 11:54
what did you implement inside the formatter?

**Comment by enikao** [comment] 2017-09-19 12:32
No changes. Interestingly, the formatter is never called (this had been my first attempt).

**Comment by cdietrich** [comment] 2017-09-19 12:32
even when calling serialize?

**Comment by enikao** [comment] 2017-09-19 12:41
If you have a look into org.eclipse.xtext.serializer.impl.Serializer, most of the serialize()-Variants do call the formatter explicitly. The serializeToRegions() variant does not. I guess that might be the problem.

**Comment by cdietrich** [comment] 2017-09-19 12:44
yes this is why i say: why do you call serializeToRegions. it makes no sense

**Comment by enikao** [comment] 2017-09-19 13:07
I need to do lots of magic on the serialized model: I want to edit only one EObject, and maybe even only some features of it, or only one feature that is not set. Therefore, I need to get the text, and the relation to TextRegions and SemanticRegions, to find the right part of the text.

Latter case:
grammar like this:
```
Event: name=ID ('[' guard=Guard ']')?
```

and an event with only a name, but no guard, and only wanting to edit the guard, I need to change the text from e. g.
```
events
  a
end
```

to
```
events
  a [
] end
```

in order to get correct autocompletion if I only show TextRegion[13, 0].

**Comment by cdietrich** [comment] 2017-09-19 13:16
i would have a look what 

org.eclipse.xtext.ide.server.formatting.FormattingService.format(Document, XtextResource, DocumentRangeFormattingParams, CancelIndicator) 

and 

org.eclipse.xtext.ui.editor.formatting2.ContentFormatter.exec(IXtextDocument, IRegion, XtextResource)


do and do something similar

**Comment by cdietrich** [comment] 2017-09-27 08:46
cc @svenefftinge any thoughts. what is the expected behaviour

**Comment by svenefftinge** [comment] 2017-09-27 09:01
@meysholdt domain

**Comment by meysholdt** [comment] 2017-09-27 17:54
Hi @enikao 

can you please verify that your implementation of `org.eclipse.xtext.formatting2.IFormatter2` is being called as part of serialization? If not, you may need to activate the `Formatter2Fragment2` in the MWE2 workflow. 

The formatter is responsible for adding whitespace to those places where they can not be taken from the node model. Even if you didn't customize the formatter, there is a fall-back that will add whitespace: `org.eclipse.xtext.formatting2.AbstractFormatter2.postProcess(IFormattableDocument, List<ITextReplacement>)`

Manipulating whitespace is something you should not in your subclass of `IFormatter2`. The classes `TextRegionAccessBuilder` and `HiddenTokenSequencer` are not intended for this. They just pass-though whitespace.

**Comment by cdietrich** [comment] 2017-12-13 09:46
i assume we should close this as "works as designed" @meysholdt @enikao what do you think

**Comment by cdietrich** [comment] 2018-01-15 12:10
since there we no objections ....

**Closed by cdietrich** 2018-01-15 12:10 UTC
