### ISSUE TITLE
[build] provide an easy to execute "create project" CLI tool

### ISSUE THREAD

**Issue by JanKoehnlein** [eclipse/xtext-core#981] opened 2018-12-17 10:27 UTC
It's nice that we can create new Xtext projects from the command line, but setting up everything in order to run the respective Java class is still a bit tedious.

We should create at least some distro zip during the build with the required libs and scripts to assemble the classpath, locate the JRE, and launch the app.

**Comment by JanKoehnlein** [comment] 2018-12-17 10:40
Why is `args4j` an optional dependency of `org.eclipse.xtext.xtext.wizard`?

**Comment by cdietrich** [comment] 2018-12-17 10:45
Cause you don’t have the command line class but you can

**Comment by JanKoehnlein** [comment] 2018-12-17 10:47
The non-CLI usecase is Eclipse, isn't it? Does it really matter to add another jar of 159k then?

**Comment by cdietrich** [comment] 2018-12-17 10:51
There is no availability in orbit maybe. Or on default platform so that we would have to repackage it to our update site 
But why is it a problem?

**Comment by JanKoehnlein** [comment] 2018-12-17 11:55
Maybe we should refactor it to use something like apache.cli.

**Comment by cdietrich** [comment] 2018-12-17 12:01
am not sure if apache cli is even more heavyweight. so the problem is that you cannot tell the gradle application plugin to include optional dependencies. @oehme do you know a way to do so?

**Comment by kthoms** [comment] 2018-12-17 12:03
> Maybe we should refactor it to use something like apache.cli.

Same there, the dependency (commons-cli then) should be optional.

**Comment by JanKoehnlein** [comment] 2018-12-17 12:18
...or, the CLI class is just placed into the wrong project. 

I still don't quite get the weight argument. As far as Orbit is concerned, does that really make a difference when a dependency is optional? And do you really search for executables at Maven? How would that make consumption easier?

This was just a quick shot at making an pretty incomplete feature a bit more usable. Likely, still not complete enough. I am open for better solutions.

**Comment by cdietrich** [comment] 2018-12-17 12:19
well i think it was ment to be used from outside where you can provide the dependencies you need.

**Comment by kthoms** [comment] 2018-12-17 12:33
The publishing to Maven Central is done by [your publishing plugin](https://github.com/TypeFox/publishing.git). Please ask @spoenemann or @dhuebner what needs to be done to package the application to a zip and deploy it with an additional classifier coordinate (`cli` could be an appropriate classifier) to artifact coordinate [`org.eclipse.xtext:org.eclipse.xtext.xtext.wizard`](https://search.maven.org/search?q=a:org.eclipse.xtext.xtext.wizard).

**Comment by cdietrich** [comment] 2019-01-16 14:04
dependency is now non optional

**Comment by szarnekow** [comment] 2023-04-17 11:09
Closing for now. Please reopen in https://github.com/eclipse/xtext if you want to contribute this feature.

**Closed by szarnekow** 2023-04-17 11:09 UTC
