### ISSUE TITLE
Traced generation - Configurable issue code is not registered

### ISSUE THREAD

**Issue by NDuemmel** [eclipse/xtext-core#544] opened 2017-11-15 09:04 UTC
Hello,

I am writing a DSL which is generated to Java.
Whenever I save my DSL file I get the following error:

> 498710 [Worker-20] ERROR org.eclipse.xtext.validation.IssueSeverities  - Configurable issue code 'org.eclipse.xtext.builder.copyJavaProblems' is not registered. Check the binding for org.eclipse.xtext.validation.ConfigurableIssueCodesProvider
> 
> !ENTRY org.apache.log4j 4 0 2017-11-14 15:33:48.136
> !MESSAGE org.eclipse.xtext.validation.IssueSeverities  - Configurable issue code 'org.eclipse.xtext.builder.copyJavaProblems' is not registered. Check the binding for org.eclipse.xtext.validation.ConfigurableIssueCodesProvider

Everything seems to work fine however, the Java code is generated.
If several classes are generated I get this error several times.
For example the following code generates two classes:

> type Point : structure {
> 	attribute x : integer;
> 	attribute y : integer;
> }
> 
> main {	
> 	variable p : Point;
> 	p.x <-- 2; 
> 	p.y <-- 3; 
> 	_output(p);
> }   

On save I get following errors:

> 756293 [Worker-20] ERROR org.eclipse.xtext.validation.IssueSeverities  - Configurable issue code 'org.eclipse.xtext.builder.copyJavaProblems' is not registered. Check the binding for org.eclipse.xtext.validation.ConfigurableIssueCodesProvider
> 
> !ENTRY org.apache.log4j 4 0 2017-11-14 15:38:05.712
> !MESSAGE org.eclipse.xtext.validation.IssueSeverities  - Configurable issue code 'org.eclipse.xtext.builder.copyJavaProblems' is not registered. Check the binding for org.eclipse.xtext.validation.ConfigurableIssueCodesProvider
> 
> 756298 [Worker-20] ERROR org.eclipse.xtext.validation.IssueSeverities  - Configurable issue code 'org.eclipse.xtext.builder.copyJavaProblems' is not registered. Check the binding for org.eclipse.xtext.validation.ConfigurableIssueCodesProvider
> 
> !ENTRY org.apache.log4j 4 0 2017-11-14 15:38:05.714
> !MESSAGE org.eclipse.xtext.validation.IssueSeverities  - Configurable issue code 'org.eclipse.xtext.builder.copyJavaProblems' is not registered. Check the binding for org.eclipse.xtext.validation.ConfigurableIssueCodesProvider
> 

Here is an excerpt from the generator:

> override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
> 		val program = resource.contents.head as Program
> 
> 		if (program !== null) {
> 			val programName = resource.URI.lastSegment.nameWithoutExtension
> 
> 			AthenaUtilGenerator.generateUtilFile(resource, fsa, context)
> 
> 			fsa.generateTracedFile("generated/" + programName + ".java", program, '''				
> 				...
> 			''')
> 		}
> 	}
> 

AthenaUtilGenerator.generateUtilFile(resource, fsa, context) calls the standard non traced generateFile method and is not causing the issue. The issues seem to be caused by the generateTracedFile method.

Both Xtend IDE and Xtext Complete SDK were updated yesterday to version 2.13.0.v20171020-0920 though the error messages were popping up before the update too.

Regards,
Nikita.

**Comment by cdietrich** [comment] 2017-11-15 09:38
i am not sure how to fix this. move the ignore pref for copy deps to xtext-core? @spoenemann @svenefftinge

**Comment by spoenemann** [comment] 2017-11-23 09:26
I have no idea, too...

**Comment by kthoms** [comment] 2017-11-30 07:51
Nikita, could you confirm that without generating with tracing the error does not appear? Or other way around, could you reproduce it with a sample project you could share? You could install the domainmodel example with the wizard and modify it.
We can't reproduce your problem so far.

**Comment by cdietrich** [comment] 2017-11-30 07:52
i can ;)

**Comment by cdietrich** [comment] 2017-11-30 07:55
code example e.g. here https://github.com/itemis/xtext-debug-example-no-xbase

**Comment by cdietrich** [comment] 2017-11-30 09:38
Fixed in 2.14

**Closed by cdietrich** 2017-11-30 09:38 UTC
Labels: bug, codegen, good first issue
