### ISSUE TITLE
File/Project Wizard: messages.properties creates additional newlines upon rebuild of xtend file

### ISSUE THREAD

**Issue by prggz** [eclipse/xtext-core#1433] opened 2020-03-27 14:05 UTC
It appears, the active annotation of the file/project wizard creates additional newline(s) in the message.properties file upon rebuild, effectively bloating it.

![image](https://user-images.githubusercontent.com/8375100/77764078-584cd380-703c-11ea-93a6-719debf4d657.png)

Sole change was that I typed a character and deleted it again to trigger rebuild.

**Comment by cdietrich** [comment] 2020-03-27 14:45
i cann t reproduce this. can you @miklossy

**Comment by miklossy** [comment] 2020-03-27 17:09
@prggz Thanks for the bug report! I can reproduce this based on the Xtext Statemachine example:
![screencast](https://user-images.githubusercontent.com/20393472/77781553-0e70e700-7056-11ea-9715-037340cb0982.gif)
@cdietrich Could you please give it another try to reproduce?

**Comment by cdietrich** [comment] 2020-03-27 17:12
no i still cant
windows problem?

**Comment by miklossy** [comment] 2020-03-27 17:13
@prggz Did you experience that behavior on Windows?

**Comment by prggz** [comment] 2020-03-27 17:25
Yes, that was on windows.

**Comment by miklossy** [comment] 2020-03-27 20:39
@cdietrich Did you try it in a host Eclipse or in a runtime Eclipse?

**Comment by cdietrich** [comment] 2020-03-27 20:40
Both. Also does not matter as I use nightly

**Comment by miklossy** [comment] 2020-03-27 20:43
Currently I can reproduce this problem only in a host Eclipse, but the problem does not occur in a runtime Eclipse -> difficult to debug. Do you have any hints why it could make a difference if the IDE is host or runtime Eclipse?

**Comment by cdietrich** [comment] 2020-03-27 20:44
Which Xtext versions do you have in them?

**Comment by miklossy** [comment] 2020-03-27 20:45
Release of Xtext 2.21.

**Comment by cdietrich** [comment] 2020-03-27 20:46
Will double check. You could remote debug with a second eclipse

**Comment by miklossy** [comment] 2020-03-28 08:38
With the help of remote debugging I could find out that the problem occurs only if the `messages.properties` file originally contains different line delimiters than the `System.lineSeparator` (e.g. Linux line endings on Windows, Windows line ending on Linux/Mac).

![screencast2](https://user-images.githubusercontent.com/20393472/77819017-dca06480-70d7-11ea-8b0c-913e1c1ec588.gif)


In such cases, the check `propertyContents.endsWith(System.lineSeparator)` in the [TemplateProcessor](https://github.com/eclipse/xtext-eclipse/blob/77876803d5427677630ccff80a51fad3706ba246/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/wizard/template/TemplateProcessor.xtend#L140) class will fail causing that an additional `System.lineSeparator` is added to the `propertyContents` variable.

@cdietrich Can you try to reproduce the problem on Mac by converting the line delimiters of the `messages.properties` file to Windows before modifying the content of the `StatemachineFileTemplateProvider.xtend` file?

**Comment by cdietrich** [comment] 2020-03-28 08:43
wont work. if ending ism `\r\n` then it still ends with `\n`
otherwise as you say: if it ends with `\n` then endsWith `\r\n` is false

can you simply replace the endsWith with "\r?\n" ????

**Comment by miklossy** [comment] 2020-03-28 09:07
No. Unfortunately endsWith expects a the suffix and not a regex. But `endsWith("\n")` could do the trick, since it matches both Windows and Linux/Mac line delimiters.

**Comment by cdietrich** [comment] 2020-03-28 09:12
then maybe use an regex to replace the endsWith
or do 2 endswiths one with `\r\n` and another with `\n`

**Comment by cdietrich** [comment] 2020-03-28 09:12
i have no idea how properties files are supposed to be line separated.
did you research and find any documentation on that?

**Comment by miklossy** [comment] 2020-03-28 09:41
I did some research but could not find any special documentation on that. Since the PR changes only the condition when to insert a newline (and not the inserted newline itself), it should be fine.

**Comment by miklossy** [comment] 2020-03-28 12:32
Thanks for the review and for the merge @tivervac !

Fixed in 2.22.

**Closed by miklossy** 2020-03-28 12:32 UTC
Labels: bug, confirmed, help_wanted
