### ISSUE TITLE
Semantic Highlighting and Validation are not working when opening Editor

### ISSUE THREAD

**Issue by tisis2** [eclipse/xtext-core#1541] opened 2020-07-08 15:37 UTC
after updating to xtext 2.20 we recognized that the semantic highlighting and the validation is not working initially when opening the editor in eclipse. we also tried to use 2.22 and it didn't work either. after editing the file everything gets updated and highlighting/validation is shown.

we updated directly from 2.13 so i dont know exactly when it broke.

i created a very small dsl and an example project to reproduce this issue. u just have to import the dsl and start a eclipse with it. in that instance u import the example project and build it. to also see the issue in validation u delete the warning from the problems view so that the resource marker is gone.

when u now open the editor the references to mya and myb are not highlighted. and the validation wont appear. as soon as u edit the file the validation and the highlighting will appear

[mySampleLanguage.zip](https://github.com/eclipse/xtext-core/files/4891670/mySampleLanguage.zip)
[mySampleProject.zip](https://github.com/eclipse/xtext-core/files/4891672/mySampleProject.zip)

**Comment by szarnekow** [comment] 2020-07-08 15:56
The validation is not triggered on newly opened editors on purpose to avoid unnecessary duplicate work - after all the markers should be in sync with the content, as long as no other open editor would have an impact on the validation result.

Coloring is correctly applied. Your highlighter does not resolve the proxy in line `Object ref = reference.eGet(MyDslPackage.Literals.REFERENCE__REF, false);` so the logic does not know what do do.

**Comment by tisis2** [comment] 2020-07-08 16:24
its correct that i get an object here thats proxy is not resolved. exactly thats the issue here. before u always got a resolved resource in the phase of highlighting. so we have an incompatibility in behavior here.

same for the validation. it was executed correct in older version when opening but not anymore.

**Comment by szarnekow** [comment] 2020-07-08 16:31
It's unfortunately the case that improvements will often lead to be perceived as bugs when looking at it from another angle.
Implementing highlighting based on resolved state without resolving the state may also be considered "not correct".

If you don't want to benefit from the faster editor response, please override `org.eclipse.xtext.ui.editor.ValidationJobScheduler.doScheduleInitialValidation(XtextDocument)` and perform an unguarded call to `document.checkAndUpdateAnnotations`

Please note, that a) with earlier versions is was coincidencial, that the validation was triggered before the highlighting kicked in and b) it may be worthwhile to avoid eGet(.., false) if you expect to see a resolved object.

**Comment by tisis2** [comment] 2020-07-09 07:24
if i understand u right, u assume that we just got a resolved resource at highlighting cause the validation was executed before in older versions?

**Comment by szarnekow** [comment] 2023-04-17 10:11
> if i understand u right, u assume that we just got a resolved resource at highlighting cause the validation was executed before in older versions?

Three years later: Yes, exactly. I'm closing this ticket since it works like it was designed.

**Closed by szarnekow** 2023-04-17 10:11 UTC
