### ISSUE TITLE
AbstractFormatter2: Indentation for single or multi-line comments is not always correct

### ISSUE THREAD

**Issue by humayun-faiz** [eclipse/xtext-core#415] opened 2017-08-09 09:21 UTC
The default indentation for single or multi-line comments does not always work properly. The following issues are being faced.

- The indentation for single line comments never worked if there wasn’t already at-least a space or a tab in-front of them.
- The indentation for single or multi-line comments never worked if they were part of the IHiddenRegion for which a decrease of indentation was set. The current understanding is that the formatter for the respective IHiddenRegion will increase the indentation for the comments contained in it and will then set an overall decrease of indentation for the upcoming strictly alternating IHiddenRegion(s) or ISemanticRegion(s).

A sample DSL file from "org.eclipse.xtext.example.domainmodel" with the mentioned problems is attached:
[domainModel.txt](https://github.com/eclipse/xtext-core/files/1210958/domainModel.txt)

Please consult the following link for further details:
[https://stackoverflow.com/questions/45568030/xtext-2-10-abstractformatter2-indentation-for-single-or-multiline-comments-is](url)

**Comment by ArneDeutsch** [comment] 2017-10-06 06:54
I have investigated. Actually it seems it is a feature, not a bug. IThere is explicit code causing this behaviour. I think the reasoning is something like:

"If you comment code (temporarily) you place the comments at the very beginning of the line. It is then nice if the formatter does NOT touch these lines. On the other hand if the comment is already indented it is probably a comment that is part of the code and hence it should be indented correctly".

The related code snippets:
`AbstractFormatter2#createCommentReplacer`
```
if (comment.getLineRegions().get(0).getIndentation().getLength() > 0)
    return new SinglelineDocCommentReplacer(comment, "//");
else
    return new SinglelineCodeCommentReplacer(comment, "//");
```
`SinglelineCodeCommentReplacer#configureWhitespace:`
`leading.getFormatting().setNoIndentation(true);`

Althought it might look like a bug from a certain perspective other formatters are quite annoying when they indent the commented code (or even format them *urgh*). Because of this I would propose to close this ticket without any change.

**Comment by kthoms** [comment] 2017-10-06 08:17
@meysholdt Do you share Arne's view? Then remove also the bug label.

**Comment by meysholdt** [comment] 2017-10-06 11:00
hi Arne,
yes, it's a feature, not a bug. in case you don't want to have it for your language you can overwrite `AbstractFormatter2#createCommentReplacer` and implement the following lines differently:
https://github.com/eclipse/xtext-core/blob/81df41e85b5bf8acbe80d240583b1c0026fbdfdd/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java#L214-L217

**Closed by meysholdt** 2017-10-06 11:00 UTC
Labels: bug, confirmed

**Comment by humayun-faiz** [comment] 2017-10-17 11:29
Please consider the below reply from my side as a response to the explanation of the bug as actually being a feature, on the stack over flow thread mentioned in the beginning of the ticket. Would also help to review the comments from the same thread to understand the problem further. Christian Dietrich provided a workaround, which is a solution to the first bug (first bullet from the initial explanation of the problem) now explained as a feature. I am not sure if its necessary to rewrite the details from stack over flow thread here again.

_"The part of placing the comments at the very beginning of the line so that they don't get indented is clear. But the indentation for the comments before the last closing brace never worked even when the comment was not in the very beginning of the line. I.e. in case they were preceded by a single space, multiple-spaces, single tab, multiple tabs or a combination of the two. The formatting resulted in one less indentation for such comments, when compared to the indentation of the comments enclosed by the same pair of opening and closing braces."_

**Comment by humayun-faiz** [comment] 2017-10-17 11:32
Also please consider reopening the ticket as a bug if it qualifies for one.
