### ISSUE TITLE
org.eclipse.xtext.tests: Unresolved proxies in XtextValidationTest.ecore

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-core#260] opened 2017-01-25 09:43 UTC
```
Description	Resource	Path	Location	Type
The feature 'eClassifier' of 'org.eclipse.emf.ecore.impl.EGenericTypeImpl@7772661d{platform:/resource/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.ecore#//Bug322875/referencesETypeFromClasspathPackage/@eGenericType}' contains an unresolved proxy 'org.eclipse.emf.ecore.impl.EClassImpl@67405b92{classpath:/org/eclipse/xtext/Xtext.ecore#//Grammar}'	XtextValidationTest.ecore	/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext	line: 1 /org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.ecore	Xtext Check (fast)
The feature 'eRawType' of 'org.eclipse.emf.ecore.impl.EGenericTypeImpl@7772661d{platform:/resource/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.ecore#//Bug322875/referencesETypeFromClasspathPackage/@eGenericType}' contains an unresolved proxy 'org.eclipse.emf.ecore.impl.EClassImpl@67405b92{classpath:/org/eclipse/xtext/Xtext.ecore#//Grammar}'	XtextValidationTest.ecore	/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext	line: 1 /org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.ecore	Xtext Check (fast)
The feature 'eReferenceType' of 'org.eclipse.emf.ecore.impl.EReferenceImpl@515df76d{platform:/resource/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.ecore#//Bug322875/referencesETypeFromClasspathPackage}' contains an unresolved proxy 'org.eclipse.emf.ecore.impl.EClassImpl@67405b92{classpath:/org/eclipse/xtext/Xtext.ecore#//Grammar}'	XtextValidationTest.ecore	/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext	line: 1 /org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.ecore	Xtext Check (fast)
The feature 'eType' of 'org.eclipse.emf.ecore.impl.EReferenceImpl@515df76d{platform:/resource/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.ecore#//Bug322875/referencesETypeFromClasspathPackage}' contains an unresolved proxy 'org.eclipse.emf.ecore.impl.EClassImpl@67405b92{classpath:/org/eclipse/xtext/Xtext.ecore#//Grammar}'	XtextValidationTest.ecore	/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext	line: 1 /org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.ecore	Xtext Check (fast)
```

Xtext.ecore is not on the classpath.

**Comment by cdietrich** [comment] 2017-01-25 09:48
Duplicate of #47

see https://github.com/eclipse/xtext-core/tree/cd_issue47 for some experiments

**Closed** 2017-01-25 09:48 UTC
