### ISSUE TITLE
bind org.eclipse.xtext.parser.antlr.IReferableElementsUnloader by default

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext-core#122] opened 2016-09-30 13:50 UTC
currently, there is a null impl bund. That causes cross references to point to dangling EObjects. A quite hard-to-diagnose problem.

**Comment by meysholdt** [comment] 2016-10-07 08:24
trivial to do and good to have a beta phase to look out if this causes trouble

**Comment by spoenemann** [comment] 2016-10-13 09:22
See #142: is that what you had in mind? Can you think of any unit test for verifying the change?

**Comment by cdietrich** [comment] 2017-02-28 13:04
it looks lke there are some places that cause trouble

**Comment by cdietrich** [comment] 2017-02-28 13:04
we should have a closer look

**Comment by meysholdt** [comment] 2017-02-28 13:12
The StackOverflow in Yakindu/statecharts#1199 happens during proxy resolution, not unloading. Proxy resolution should never cause an infinite recursion, no matter what proxies are resolved. Not sure why you suspect the unloader.

**Comment by cdietrich** [comment] 2017-02-28 13:13
the analysis of @andreasmuelder revealed that. ill do some debugging on that

**Comment by andreasmuelder** [comment] 2017-02-28 13:20
@meysholdt I don't suspect the unloader, the unloader ist the cause.

binder.bind(IReferableElementsUnloader.class).to(IReferableElementsUnloader.NullUnloader.class);

resolves the problem.

**Comment by cdietrich** [comment] 2017-02-28 14:14
@meysholdt problem happens when 

featureValueList (PartialParsingHelper) is actually a org.eclipse.emf.ecore.util.EObjectContainmentEList.Resolving<E>

**Comment by meysholdt** [comment] 2017-02-28 14:42
It's ok if the list is a EObjectContainmentEList.Resolving. But it shouldn't contain any proxies, because if the `PartialParsingHelper` proxifies (the unloader, actually) a containment reference, it is also obligated to replace that proxy with a new parse result.

**Comment by cdietrich** [comment] 2017-02-28 14:43
yes but the element that is unloaded is actually a proxy (that is what onloading does)

**Comment by meysholdt** [comment] 2017-02-28 14:47
do you have a stack trace from 
`org.eclipse.xtext.parser.impl.PartialParsingHelper.reparse(IParser, IParseResult, ReplaceRegion)` to 
`org.eclipse.emf.ecore.util.EcoreUtil.resolve(EObject, ResourceSet)`
?

**Comment by cdietrich** [comment] 2017-02-28 14:53
```
EcoreUtil.resolve(EObject, EObject) line: 258	
SimpleScopeImpl(BasicEObjectImpl).eResolveProxy(InternalEObject) line: 1477	
EObjectContainmentEList$Resolving<E>(EcoreEList<E>).resolveProxy(EObject) line: 206	
EObjectContainmentEList$Resolving<E>(EcoreEList<E>).indexOf(Object) line: 413	
EObjectContainmentEList$Resolving<E>(AbstractEList<E>).set(int, E) line: 261	
PartialParsingHelper.reparse(IParser, IParseResult, ReplaceRegion) line: 162	
```

**Comment by meysholdt** [comment] 2017-02-28 15:05
good catch! That's a bug indeed.
I propose `PartialParsingHelper.reparse()` should call `unloadSemanticObject()` *after* having detached the semantic object from the AST.

**Comment by cdietrich** [comment] 2017-02-28 15:32
genmodel needs a containmentProxies="true" to get this situation

**Comment by szarnekow** [comment] 2023-04-18 09:59
Closing since this is, in fact, already implemented. Subsequent discussion points are related but also unrelated.

**Closed by szarnekow** 2023-04-18 09:59 UTC
Labels: enhancement
