### ISSUE TITLE
Generation error when using ExternalAntlrLexerFragment

### ISSUE THREAD

**Issue by mcorino** [eclipse/xtext-core#1518] opened 2020-06-04 12:15 UTC
I've been playing around with the org.eclipse.xtext.xtext.generator.parser.antlr.ex.ExternalAntlrLexerFragment implementation in Xtext 2.21 in order to use a custom Antlr grammar and found that this fragment does not function out of the box.
Using a fragment declaration like:

    fragment = parser.antlr.ex.ExternalAntlrLexerFragment {
        lexerGrammar = "org.whatever.something.lexer.Custom"
        runtime = true
        antlrParam = "-lib"	
        antlrParam = "${rootPath}/src-gen/org/whatever/something/lexer"
    }

I get file access errors after the lexer and parser have been generated from the custom grammar in org.whatever.something.lexer.Custom.g for the file Custom.java.
It turns out the fragment does not take into account the Antlr generation suffix 'Lexer' for the generated lexer class (generated in CustomLexer.java).
After I created my own implementation of the fragment in a small patch plugin which added the suffix in five places I was successfully able to use a drop in custom grammar.

**Comment by cdietrich** [comment] 2020-06-04 12:17
hi, can you please provide a small reproducer?

**Comment by cdietrich** [comment] 2020-06-04 12:19
in mwe and codetemplates it looks like

`lexerGrammar = "org.eclipse.xtext.ui.codetemplates.ui.contentassist.SingleCodetemplateContentAssistLexer"
`

**Comment by miklossy** [comment] 2020-06-04 12:27
In the [Eclipse GEF DOT](https://github.com/eclipse/gef/wiki/DOT-User-Guide) project the [GenerateDot.mwe2](https://github.com/eclipse/gef/blob/master/org.eclipse.gef.dot/src/org/eclipse/gef/dot/internal/language/GenerateDot.mwe2#L143-L149) workflow contains:
```
fragment = org.eclipse.xtext.generator.adapter.FragmentAdapter {
				fragment = parser.antlr.ex.ExternalAntlrLexerFragment {
					// A grammar file with .g will be expected in this package (should be stored in src folder)
					lexerGrammar = "org.eclipse.gef.dot.internal.language.parser.antlr.lexer.CustomInternalDotLexer"
					runtime = true
				}
			}
```

**Comment by mcorino** [comment] 2020-06-04 12:50
To reproduce the initial errors (in Xtext 2.21):

- create the standard Xtext Domainmodel examples
- create a package org.eclipse.xtext.example.domainmodel.lexer under the 'src' folder
- copy the Xtext generated InternalDomainmodel.g grammar file to the previously created package with the name 'Custom.g'
- replace the StandardLanguage {} section in GenerateDomainmodel.mwe2 with the following

	    language = XtextGeneratorLanguage {
			name = "org.eclipse.xtext.example.domainmodel.Domainmodel"
			fileExtensions = "dmodel"
			referencedResource = "platform:/resource/org.eclipse.xtext.xbase/model/Xbase.genmodel"	     
	        fragment = grammarAccess.GrammarAccessFragment2 {}
	        fragment = ecore.EMFGeneratorFragment2 {}
	        fragment = serializer.SerializerFragment2 {
	        	generateStub = false
	        }
	        fragment = resourceFactory.ResourceFactoryFragment2 {}
	        fragment = parser.antlr.XtextAntlrGeneratorFragment2 {
				options = {
					backtrack = false
					backtrackLexer = false
					classSplitting = true
					fieldsPerClass = "500"
					skipUnusedRules = true
				}
	        }
	        fragment = parser.antlr.ex.ExternalAntlrLexerFragment {
	        	lexerGrammar = "org.eclipse.xtext.example.domainmodel.lexer.Custom"
	        	runtime = true
	        	antlrParam = "-lib"	
	        	antlrParam = "${rootPath}/src-gen/org/eclipse/xtext/example/domainmodel/lexer"
	        }
	        
	        fragment = validation.ValidatorFragment2 {
				// composedCheck = "org.eclipse.xtext.validation.NamesAreUniqueValidator"
				// Generates checks for @Deprecated grammar annotations, an IssueProvider and a corresponding PropertyPage
				generateDeprecationValidation = true
	        }
	        fragment = scoping.ImportNamespacesScopingFragment2 {}
	        fragment = exporting.QualifiedNamesFragment2 {}
	        fragment = builder.BuilderIntegrationFragment2 {}
	        fragment = generator.GeneratorFragment2 {
				generateXtendStub = true
	        }
	        fragment = formatting.Formatter2Fragment2 {
				generateStub = true
				generateXtendStub = true
	        }
	        fragment = ui.labeling.LabelProviderFragment2 {}
	        fragment = ui.outline.QuickOutlineFragment2 {}
	        fragment = ui.outline.OutlineTreeProviderFragment2 {}
	        fragment = ui.quickfix.QuickfixProviderFragment2 {}
	        fragment = ui.contentAssist.ContentAssistFragment2 {}
	        fragment = junit.JUnitFragment {
	        	junitVersion = "5"
	        }
	        fragment = ui.refactoring.RefactorElementNameFragment2 {}
	        fragment = types.TypesGeneratorFragment2 {}
	        fragment = xbase.XtypeGeneratorFragment2 {}
	        fragment = xbase.XbaseGeneratorFragment2 {}
	        fragment = ui.templates.CodetemplatesGeneratorFragment2 {}
	        fragment = ui.compare.CompareFragment2 {}
	        fragment = web.WebIntegrationFragment {
	            framework = "Ace"
	        }
	        fragment = ui.projectWizard.TemplateProjectWizardFragment {}
	        fragment = ui.fileWizard.TemplateFileWizardFragment {}
		}

- run the MWE2 workflow

To fix these problems (in Xtext 2.21):
- patch the `doGenerate()` method of the `ExternalAntlrLexerFragment` class like this:

```java
protected void doGenerate() {
  if (runtime) {
    StringConcatenationClient binding = new StringConcatenationClient() {
      @Override
      protected void appendTo(TargetStringConcatenation target) {
        target.append("binder.bind(" + Lexer.class.getName() + ".class)"+
            ".annotatedWith(com.google.inject.name.Names.named(" +
            "org.eclipse.xtext.parser.antlr.LexerBindings.RUNTIME" +
            ")).to(" + lexerGrammar +"Lexer.class);");
      }
    };
    new GuiceModuleAccess.BindingFactory().addConfiguredBinding("RuntimeLexer", binding).contributeTo(getLanguage().getRuntimeGenModule());
  }
  if (highlighting) {
      if (this.getProjectConfig().getEclipsePlugin().getRoot() != null) {
        StringConcatenationClient binding = new StringConcatenationClient() {
          @Override
          protected void appendTo(TargetStringConcatenation target) {
            target.append("binder.bind(" + Lexer.class.getName() + ".class)"+
                ".annotatedWith(com.google.inject.name.Names.named(" +
                "org.eclipse.xtext.ide.LexerIdeBindings.HIGHLIGHTING" +
                ")).to(" + lexerGrammar +"Lexer.class);");
          }
        };
        new GuiceModuleAccess.BindingFactory().addConfiguredBinding("HighlightingLexer", binding).contributeTo(getLanguage().getEclipsePluginGenModule());
      }
    }
    if (contentAssist) {
      if (this.getProjectConfig().getGenericIde().getRoot() != null) {
        StringConcatenationClient binding = new StringConcatenationClient() {
          @Override
          protected void appendTo(TargetStringConcatenation target) {
            target.append("binder.bind(org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer.class)"+
                ".annotatedWith(com.google.inject.name.Names.named(" +
                "org.eclipse.xtext.ide.LexerIdeBindings.CONTENT_ASSIST" +
                ")).to(" + lexerGrammar +"Lexer.class);");
          }
        };
        new GuiceModuleAccess.BindingFactory().addConfiguredBinding("ContentAssistLexer", binding).contributeTo(getLanguage().getIdeGenModule());
    
      } 
      if (this.getProjectConfig().getEclipsePlugin().getRoot() != null) {
        StringConcatenationClient binding = new StringConcatenationClient() {
          @Override
          protected void appendTo(TargetStringConcatenation target) {
            target.append("binder.bind(org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer.class)"+
                ".annotatedWith(com.google.inject.name.Names.named(" +
                "org.eclipse.xtext.ide.LexerIdeBindings.CONTENT_ASSIST" +
                ")).to(" + lexerGrammar +"Lexer.class);");
          }
        };
        new GuiceModuleAccess.BindingFactory().addConfiguredBinding("ContentAssistLexer", binding).contributeTo(getLanguage().getEclipsePluginGenModule());
      }
    }
    
    
  
  
  IXtextGeneratorFileSystemAccess srcGenFsa = this.getProjectConfig().getRuntime().getSrcGen();
  IXtextGeneratorFileSystemAccess srcFsa = this.getProjectConfig().getRuntime().getSrc();
  if (contentAssist || highlighting) {
    if (this.getProjectConfig().getGenericIde().getRoot() != null) {
      srcGenFsa = this.getProjectConfig().getGenericIde().getSrcGen();
      srcFsa = this.getProjectConfig().getGenericIde().getSrc();
    } else {
      srcGenFsa = this.getProjectConfig().getEclipsePlugin().getSrcGen();
      srcFsa = this.getProjectConfig().getEclipsePlugin().getSrc();
    }
  }
  String srcGenPath = srcGenFsa.getPath();
  String srcPath = srcFsa.getPath();
  String grammarFile = srcPath + "/" + getLexerGrammar().replace('.', '/') + ".g";
  String generateTo = "";
  if (getLexerGrammar().lastIndexOf('.') != -1) {
    generateTo = getLexerGrammar().substring(0, getLexerGrammar().lastIndexOf('.'));
  }
  generateTo = srcGenPath + "/" + generateTo.replace('.', '/');
  addAntlrParam("-fo");
  addAntlrParam(generateTo);
  final String encoding = getCodeConfig().getEncoding();
  getAntlrTool().runWithEncodingAndParams(grammarFile, encoding, getAntlrParams());
  
  TypeReference lexerType = new TypeReference(getLexerGrammar()+"Lexer");
  splitParserAndLexerIfEnabled(srcGenFsa, null /* parser */, lexerType);
  normalizeTokens(srcGenFsa, getLexerGrammar().replace('.', '/') + ".tokens");
  suppressWarnings(srcGenFsa, lexerType);
  normalizeLineDelimiters(srcGenFsa, lexerType);
}
```
Note the addition of the "Lexer" suffix in five places.

**Comment by cdietrich** [comment] 2020-06-04 12:52
wouldnt that lead to LexerLexer then?

**Comment by mcorino** [comment] 2020-06-04 13:00
Not in my environment. The Antlr generation produces `CustomLexer.java` and `CustomParser.java` form grammar `Custom.g` but the fragment class uses the `lexerGrammar` setting (which is the grammar filename without `.g`) to generate binding directives and the lexerType TypeReference without taking into account the Antlr suffixes.

**Comment by szarnekow** [comment] 2020-06-04 13:40
Please note that a custom _parser_ is not supported by any means. The fragment works correctly as designed (therefore the name ExternalAntlrLexerFragment).
Please use a pure lexer grammar along with that fragment.

**Comment by mcorino** [comment] 2020-06-04 13:51
Ah, my bad. There is not much documentation regarding this fragment en what is there is not really clear. No matter, just experimenting. Will leave it for what it is.

**Comment by szarnekow** [comment] 2020-06-07 16:21
I'm closing this ticket.

**Closed by szarnekow** 2020-06-07 16:21 UTC
